### ISSUE TITLE
Gravity broken on GNU/Linux

### ISSUE THREAD

**Issue by izobilje** [SuperNunb/crazyIce#3]
Hi! I'm using Python 2.7.16 and Pygame 1.9.5 on Arch Linux. The gravity is broken. I can jump, but the character never falls down. It's because my Python assumes the HEIGHT variable is integer and then calculates AVATAR_GRAV as integer ( = 0 ). I solved it by changing a line in settings.py to AVATAR_GRAV = float(HEIGHT) / 1000

There is another type-related issue - the scores are displayed like 1000.0 (with .0 at the end), but it doesn't affect the gameplay.

**Comment by cbayles1** [comment]
Thanks! Would you mind making a branch or something with that change in it? I'll merge it once I get the chance; I'm kind of busy with other stuff right now, so I can't make the change myself.

**Comment by cbayles1** [comment]
Actually never mind. I'm able to now, and that shouldn't be too difficult of a fix. 
Thank you for telling me!

**Comment by cbayles1** [comment]
Ok, I just updated it with the first fix. The second one I'm guessing happened because you had an older version of the game. In the current version, line 342 in main.py should fix that.

**Comment by izobilje** [comment]
Lives and score are still displayed like "3.0". The fix would be to use "int" instead of "round" in 340 and 342, as in 

> lifeLabel = str("LIVES: " + str(int(self.lives)))

The gravity is fixed so I'm closing this issue. Thanks!
